Add module for dispersion image calculation
DASDAE/dascore pull request #275
Opened 2023-10-05 17:24 UTC by ariellellouch

This module was created to generate dispersion images directly from patches. It uses the distance coordinates to compute a dispersion image using the phase-shift method. 

## Checklist

I have (if applicable):

- [ ] referenced the GitHub issue this PR closes.
- [X] documented the new feature with docstrings or appropriate doc page.
- [ ] included a test. See [testing guidelines](https://dascore.org/contributing/testing.html).
- [X] your name has been added to the contributors page (docs/contributors.md).
- [X] added the "ready_for_review" tag once the PR is ready to be reviewed.

2023-10-05 19:35 UTC, d-chambers commented
Hey @ariellellouch, great start! The docstring looks comprehensive and the method and its citations look solid. I will try to find some time in the next few days for a proper review (which means brushing up on the method), but after a quick glance there are a couple of things you can work on in the meantime:

1. testing

We need to ensure DASCore's test suite exercises the new code, preferably every line. To do that you would create a new python file (`tests/test_transform/test_dispersion.py`). The simplest test file in the transforms module you can reference as an example is `test_fft.py`. Then you can run your tests with pytest like: `pytest tests/test_transforms/test_dispersion.py`.  Let me know if you need any help with this, I know pytest (and automated testing in general) can be a bit of a learning curve if you are new to it.

2.  `DispersionParameterError` is probably a little too specific. I would recommend just using `ParameterError` which is already in the exceptions module.

3. If your transform requires dimensions "time" and "distance" the easiest way to ensure this is the case is to use the `required_dims` parameter of [`patch_function`](https://dascore.org/api/dascore/utils/patch/patch_function.html)

e.g., 

```python 
@patch_function(required_dims=("time", "distance"))
def phase_shift(
    patch: PatchType, vels: Sequence[float], direction: str, approxdf: float = 0.0
) -> PatchType:
```

Great work so far.

2023-10-08 12:13 UTC, ariellellouch commented
Hi @d-chambers,

I added a basic testing unit, as well as fixed your other comments. Sorry if this is amateur coding, but I did my best 

Ariel

2023-10-12 03:07 UTC, d-chambers requested changes
Hey @ariellellouch,

I finally got a chance to go through this, sorry for the delay. There are a few things in the comments I have listed below.  I tried to list out not only the suggested changes but the reasoning for them. Let me know if you have any questions and sorry if I am asking some dumb questions, I am new to MASW.

I am also a bit concerned about testing the correctness of the output, not just the shape and coordinates, but we don't have a dispersive example patch. We should look into making a synthetic one (probably in a different PR), then ensuring the peaks are in the right places. 

If you have too much going on right now (which is completely understandable) I can take a few minutes towards the end of the week and push this over the finish line. Whatever works for you. 

Thanks to @ahmadtourei who helped me do the review.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    f[1] - f[0]
This line has no effect

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    patch: PatchType, vels: Sequence[float], direction: str, approxdf: float = -1.0
- maybe "vels" would be better as "phase_velocities" ? 
- approxdf -> approx_resolution? 
- Default values are idiomatically set to `None` 
- Should we raise an Error if approx_resolution <= 0?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    Inspired by https://geophydog.cool/post/masw_phase_shift/.
The first line of the docstring needs to be a single line so it fits nicely in the tables eg:
![image](https://github.com/DASDAE/dascore/assets/11671536/c517a0ed-b198-4d2f-a22b-ba7c58a3184d)

So probably move the inspired by to its own notes section, eg

```python 
"""
Compute dispersion images using the phase-shift method.

...

Notes
---------
 - See also @park_1999
 - Inspired by https://geophydog.cool/post/masw_phase_shift/.
"""
```
Note, we should add park et al. 1999 to docs/references.bib then cite it like above. See the [citing references section](https://dascore.org/contributing/documentation.html#referencing-publications). Also, shouldn't it be Park et al., 1998?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    assert n == nt
Would be better `assert (nt, nchan) == patch_cop.shape`?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +        Indicating whether the event is down-dip ('ltr') or up-dip ('rtl')
Maybe I misunderstand, but if distance is from the source, isn't this fixed?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    words, data are effectively mapped along a 2-D line.
So should distance always start at 0?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +                sum(np.exp(preamb * w[fi] / vels[ci] * dist) * fft_d[:, fi])
Does this need to be normalized by `N`? For example in Olafsdottir et al., 2018 EQ 6 or figure 3. 

Olafsdottir, Elin Asta, Sigurdur Erlingsson, and Bjarni Bessason. "Tool for analysis of multichannel analysis of surface waves (MASW) field data and evaluation of shear wave velocity profiles of soils." Canadian Geotechnical Journal 55.2 (2018): 217-233.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    attrs = dict(category="Dispersion")
I think this should be:

```python 
attrs = patch.attrs.update(category="dispersion")
```
so that `category` is added/updated but everything remains the same.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +def phase_shift(
`phase_shift` is ambiguous in what it might do.  Maybe `dispersion_phase_shift` would be a more descriptive name?

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +        raise ParameterError("Direction can only be ltr or rtl")
We need a test for these exceptions, but they aren't too hard to write. For example:

```python
test_bad_direction_raises(self, random_patch):
    """Ensure a bad direction param raises an error."""
    with pytest.raises(ParameterError):
        random_patch.phase_shift(direction="not valid")
```

Is all it takes.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +        patch_cop.transpose("distance", "time")
This line has no effect. Remember, patch function return new patches, they don't modify the data in place. You can just do:

```python
patch_cop = patch_cop.transpose("distance", "time")
```
but since we can call `transpose` above we can just delete these lines.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    patch_cop = patch.new()
This line also does nothing. Since there isn't any new data the old patch is simply returned. This is safe because patches and their content are immutable.

You probably want to do this instead:

```python
patch_cop = patch.convert_units(distance="m").transpose("distance", "time")
```

then delete the `set_units` and `transpose` calls later on. Both `convert_units` and `transpose` are smart enough to do nothing if they aren't needed, so the cost of calling them is negligible.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +                sum(np.exp(preamb * w[fi] / vels[ci] * dist) * fft_d[:, fi])
These for loops bother me a bit since python is not very fast at looping. I wonder if there is a way to push these down to numpy with some broadcasting magic. I will think on it.

2023-10-12 03:07 UTC, d-chambers commented on dascore/transform/dispersion.py
> +    return disp_patch
Same issue here as mentioned above, mainly that 

```python
disp_patch.set_units(velocity="m/s", frequency="Hz") 
```
returns a new patch which doesn't get assigned to a variable so it has no effect. Instead you want:

```python
return disp_patch.set_units(velocity="m/s", frequency="Hz")
```

Or you could use an intermediate variable.

2023-10-12 03:07 UTC, d-chambers commented on tests/test_transform/test_dispersion.py
> +        assert any(dimfreq)
It's simpler to just do:

```python
assert "velocity" in dispersion_patch.dims
assert "distance" in dispersion_patch.dims
```

2023-10-12 07:27 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    f[1] - f[0]
Done

2023-10-12 07:36 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    patch: PatchType, vels: Sequence[float], direction: str, approxdf: float = -1.0
Done. Assuming I understood the third point (I set approx_resolution to None by default)

2023-10-12 07:45 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    Inspired by https://geophydog.cool/post/masw_phase_shift/.
Done

2023-10-12 07:45 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    assert n == nt
Done

2023-10-12 07:48 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    words, data are effectively mapped along a 2-D line.
No. The phase method works in a "relative" way - if we start at distance X, the phase shift of the first channel will be non-zero, but it's not a problem.

2023-10-12 07:48 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +        Indicating whether the event is down-dip ('ltr') or up-dip ('rtl')
You are right, actually. We should have the user order the data the right way. 
Deleted this option.

2023-10-12 07:54 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +                sum(np.exp(preamb * w[fi] / vels[ci] * dist) * fft_d[:, fi])
Good catch! 
done

2023-10-12 08:08 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +def phase_shift(
Done

2023-10-12 08:10 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    attrs = dict(category="Dispersion")
Done

2023-10-12 08:10 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +        raise ParameterError("Direction can only be ltr or rtl")
Deleted this flag (previous comment)

2023-10-12 08:16 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    patch_cop = patch.new()
Thanks, done

2023-10-12 08:19 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +    return disp_patch
Done

2023-10-12 08:21 UTC, ariellellouch commented on tests/test_transform/test_dispersion.py
> +        assert any(dimfreq)
"frequency" and not "distance", but done :)

2023-10-12 08:22 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +        patch_cop.transpose("distance", "time")
Done.

2023-10-12 08:22 UTC, ariellellouch commented on dascore/transform/dispersion.py
> +                sum(np.exp(preamb * w[fi] / vels[ci] * dist) * fft_d[:, fi])
I am leaving this open and will try something myself.
One thing that we could consider is numba, but I don't know if you like the dependency.

2023-10-13 21:18 UTC, d-chambers commented
Good work, it looks much better.

> I have a synthetic dataset ready for that, but the question is whether I should open a new PR or piggyback on this one? It's not trivial how to compare to exact results because there are numerical resolution issues.

If you are up to it, adding it here is probably better. That way the example can actually use a patch which has some dispersion and make a nicer plot.  I think the steps for you will more or less be these:

1. Create a patch from your synthetic data
2. Save the patch to disk using dasdae format (we will add other writing formats later on)
3. clone the [dasdae test_data repo](https://github.com/DASDAE/test_data)
4. add your data files there, and commit it. Then push either to the master branch, or make another branch and open a PR if you can't
5. calculate file hash using [`pooch.file_hash`](https://www.fatiando.org/pooch/latest/api/generated/pooch.file_hash.html)
6. Create a new entry in dascore's data registry (dascore/data_registry.txt)
7. Create a new patch example function in dascore/examples.py. You can use [example_event_1](https://github.com/DASDAE/dascore/blob/12e2abf3fec9f18bc17e9bdbfc5bbdea64f9f524/dascore/examples.py#L172-L180) as an example. 
8. Update your docstring in `dispersion_phase_shift` to load and use this new patch. For example, if you select the name "dispersive_event" just swap that out for "example_event_1". 

[This](https://dascore.org/contributing/adding_test_data.html#adding-a-data-file)  section of the docs also shows how to add an example file.

2023-10-13 21:22 UTC, d-chambers commented
Also when you generate your example patch its much nicer if you remember to set the units before saving it. I forgot to do that on the "example_event_1" patch which is why you had use the `set_units("mm/(m*s)", distance='m', time='s')` line in your docstring.

2023-10-13 21:51 UTC, d-chambers commented
I found a few other small things that i just fixed. Mainly, adding tests for all the raised exceptions and deleting the docstring line which described the removed parameter. 

I am probably a little extreme with how much effort I spend trying to get 100% code coverage, but I did find a subtle bug by doing it: 

```python
    if not np.all(np.diff(phase_velocities)) > 0:
```
should be:

```python
    if not np.all(np.diff(phase_velocities) > 0):
```

In the first case the `Parameter` is never raised unless a diff in the array is 0 (some diffs can happily be less than 0).

2023-10-16 10:55 UTC, ariellellouch commented
This is actually a pretty good catch - sorry I missed the parenthesis.

1) Added the example as you suggested! It works for me, besides a small problem that I don't know how to fix.
This is how I create the patch:

attrs = dict(
    data_type="velocity",
    id="dispersion_data",
    data_units="m/s",
    data_category="DAS"
)

But for some reason the units are not kept and "revert" to mm/ m / s. Maybe you can help elucidate the mystery...

2) I added what I think is important functionality (especially for run-tume) to limit the frequency range in which the dispersion is calculated. Especially for surface waves, you may want let's say 5-30 Hz, but data sampled at 2000 Hz would be pretty painful. So, I added min/max frequency. I tried to follow your tests convention, hope it is OK - feel free to change. 

3) Added more testing to the functionality in (2)

See you at the sprint.
Ariel

2023-10-16 12:18 UTC, d-chambers commented
> But for some reason the units are not kept and "revert" to mm/ m / s. Maybe you can help elucidate the mystery...

When I do this:
```python
import dascore as dc

dc.get_example_patch("dispersion_event")
```

I get this patch:

![image](https://github.com/DASDAE/dascore/assets/11671536/c0b9f6a8-a215-4040-a31a-a06b9d3d8c8c)

which has data units of "m/s". Is this not the case for you, or are the units getting switched after the dispersion calculations?

2023-10-16 12:30 UTC, ariellellouch commented
@d-chambers 
Yes, but when I run the example, the units of the transformed dispersion patch are something else , and I have no idea why...

2023-10-16 13:48 UTC, d-chambers commented
Maybe I am missing something, but this line in the example:

```python       
 .set_units("mm/(m*s)", distance='m', time='s')
````

will set the data units to "mm/(m*s)". Instead, you can just do:

```python       
 .set_units(distance='m', time='s')
````

to leave the data units alone on only set the coordinate units. Does that solve the issue?

2023-10-16 13:54 UTC, ariellellouch commented
Oh, such a stupid mistake. Sorry about that - I removed all the unnecessary processing steps.

Should be good to review now!

2023-10-16 15:51 UTC, d-chambers approved these changes

2023-10-16 15:54 UTC, merged

2023-10-16 15:54 UTC, d-chambers commented
🥳