Wiggleplot
DASDAE/dascore pull request #95
Opened 2022-12-20 22:51 UTC by aissah

Wiggle plot module data

2022-12-22 14:28 UTC, d-chambers commented
Ready for review @aissah or are you still working on this?

2022-12-22 15:36 UTC, aissah commented
> Ready for review @aissah or are you still working on this?

I am still working on it. Will probably finish it by noon.

2022-12-22 16:27 UTC, d-chambers commented
Ok, no rush. You can just add the ready_for_review tag on right when you are done.

2022-12-23 18:27 UTC, d-chambers requested changes
Just a few small suggestions. Can you also post a screenshot of the output in this thread for future reference?

2022-12-23 18:27 UTC, d-chambers commented on dascore/viz/wiggle.py
> +Module for wiggle plotting.
I like the description. Short and to the point.

2022-12-23 18:27 UTC, d-chambers commented on dascore/viz/wiggle.py
> +@patch_function()
It looks like `wiggle` expects dimensions of `time` and `distance`. This is fine, and a good way to ensure this is the case is to add `required_dims=('time', 'distance')` to the `patch_function` decorator.

2022-12-23 18:27 UTC, d-chambers commented on dascore/viz/wiggle.py
> +        maxOfTraces = abs(data).max(axis=1)
Small nit pick, but 🎵 [camel case is not for python, never ever](https://www.youtube.com/watch?v=hgI0p1zf31k) 🎵 

So, `max_of_traces` rather than `maxOfTraces`, same for other variables. I need to add something to the linter about this.

2022-12-23 18:27 UTC, d-chambers commented on dascore/viz/wiggle.py
> +        wher = data[a] < 0
"where" rather than "wher"?

2022-12-23 18:27 UTC, d-chambers commented on dascore/viz/wiggle.py
> +    """
Consider [adding an example](https://dascore.org/contributing/documentation.html#examples-in-docstrings)

2022-12-31 21:49 UTC, aissah commented on dascore/viz/wiggle.py
> +@patch_function()
The x-axis is always time but it doesn't require any specific input dimensions. Could you point out which line gives that impression?

2022-12-31 21:50 UTC, aissah commented on dascore/viz/wiggle.py
> +        maxOfTraces = abs(data).max(axis=1)
Ok, this song is a discovery. I have made the changes and will allow pep8 to guide my path in the future

2022-12-31 21:53 UTC, aissah commented on dascore/viz/wiggle.py
> +        wher = data[a] < 0
I am always somehow reluctant to use the name of an optional input as a variable name, makes me very anxious. But I will sacrifice myself for the greater good of dasdae

2022-12-31 21:54 UTC, aissah commented on dascore/viz/wiggle.py
> +    """
I am going to work on this but I might come by for some help next week

2022-12-31 21:56 UTC, aissah commented on dascore/viz/wiggle.py
> +Module for wiggle plotting.
> 

![wiggles_ss](https://user-images.githubusercontent.com/78217939/210156292-0f041a11-4e4d-4ec9-a1be-a2a42ba184dc.png)
![wiggles_sstime](https://user-images.githubusercontent.com/78217939/210156293-c92dc1f9-3043-4ae5-81cf-9a8898e34d5a.png)

Did this work? The boring examples don't leave much to be seen

2023-01-11 19:20 UTC, d-chambers commented
Hey @aissah 

[Here](https://dascore.org/contributing/documentation.html#doc-strings) is the section that explains docstrings. Let me know if it ins't clear and I while expand the section.

2023-01-26 17:04 UTC, d-chambers commented
Rebased to master, should be good after that.

2023-01-27 19:44 UTC, merged